# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run linting
      run: |
       go fmt github.com/godofprodev/tally/api
       go vet github.com/godofprodev/tally/api

    - name: Build
      run: go build github.com/godofprodev/tally/api -v ./...

    - name: Test
      run: go test github.com/godofprodev/tally/api -v ./...
